### ISSUE TITLE
API returns duplicate dates for tests, intensive care

### ISSUE THREAD

**Issue by gapan** [Covid-19-Response-Greece/covid19-greece-api#10]
Getting data using the https://covid-19-greece.herokuapp.com/total-tests endpoint, currently returns (partial output):
```
{"date":"2020-08-31","tests":949367},
{"date":"2020-08-31","tests":966346}
```
Two different values for the same date.

Similarly, for https://covid-19-greece.herokuapp.com/intensive-care, I get:
```
{"date":"2020-08-31","intensive_care":36},
{"date":"2020-08-31","intensive_care":38}
```

**Comment by billmats96** [comment]
The latter values refer to 2020-09-01. The endpoints have been updated.
